/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hongdian_usbcamera_Camera */

#ifndef _Included_com_hongdian_usbcamera_Camera
#define _Included_com_hongdian_usbcamera_Camera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hongdian_usbcamera_Camera
 * Method:    openCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hongdian_usbcamera_Camera_openCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_hongdian_usbcamera_Camera
 * Method:    peekFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hongdian_usbcamera_Camera_peekFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_hongdian_usbcamera_Camera
 * Method:    fillFrame
 * Signature: (Lcom/hongdian/usbcamera/FrameContainer;)V
 */
JNIEXPORT void JNICALL Java_com_hongdian_usbcamera_Camera_fillFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hongdian_usbcamera_Camera
 * Method:    closeCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hongdian_usbcamera_Camera_closeCamera
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
